// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH1KQgeg29-Dz-QYd1J-e77Okpya9msUI',
    appId: '1:128922768153:web:55f2ad40d7957dbe846b88',
    messagingSenderId: '128922768153',
    projectId: 'atma-vichara',
    authDomain: 'atma-vichara.firebaseapp.com',
    storageBucket: 'atma-vichara.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj7RxbBycSbUt3OaKy79q3o7tHBhFbj8k',
    appId: '1:128922768153:android:8c974758e5f2ac24846b88',
    messagingSenderId: '128922768153',
    projectId: 'atma-vichara',
    storageBucket: 'atma-vichara.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDQs8Mi4g1uU5EtUxQJD94NmEZdm8ijFc',
    appId: '1:128922768153:ios:f4bcb1b861c8c303846b88',
    messagingSenderId: '128922768153',
    projectId: 'atma-vichara',
    storageBucket: 'atma-vichara.appspot.com',
    iosBundleId: 'com.example.atmaVicharaGemastik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDQs8Mi4g1uU5EtUxQJD94NmEZdm8ijFc',
    appId: '1:128922768153:ios:f4bcb1b861c8c303846b88',
    messagingSenderId: '128922768153',
    projectId: 'atma-vichara',
    storageBucket: 'atma-vichara.appspot.com',
    iosBundleId: 'com.example.atmaVicharaGemastik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH1KQgeg29-Dz-QYd1J-e77Okpya9msUI',
    appId: '1:128922768153:web:9e98b6535ae47dac846b88',
    messagingSenderId: '128922768153',
    projectId: 'atma-vichara',
    authDomain: 'atma-vichara.firebaseapp.com',
    storageBucket: 'atma-vichara.appspot.com',
  );
}
